### ISSUE TITLE
CRS problem

### ISSUE THREAD

**Issue by matamadio** [MamadioCMCC/HazardRiskScripts#9]
I tried to run the tool on some rasters, the tool runs instanctly and returns excel with: 
Could not process rastername.tif with shapename.shp, incorrect CRS.

[stats.zip](https://github.com/MamadioCMCC/HazardRiskScripts/files/4160284/stats.zip)

However the metadata for both .tif and .shp is the same:
+proj=utm +zone=32 +ellps=intl +towgs84=-87,-98,-121,0,0,0,0 +units=m +no_defs

**Comment by ConnectedSystems** [comment]
The issue is caused by the shapefile having a EPSG code defined, while the raster does not.

If I inspect the WKT string of the raster, I get this:
```
PROJCS["ED50_UTM_zone_32N",GEOGCS["GCS_European_1950",DATUM["European_Datum_1950",SPHEROID["International_1924",6378388,297,AUTHORITY["EPSG","7022"]],AUTHORITY["EPSG","6230"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]
```

While the WKT string from the shapefile is defined as:

```
PROJCS["ED50 / UTM zone 32N",GEOGCS["ED50",DATUM["European_Datum_1950",SPHEROID["International 1924",6378388,297,AUTHORITY["EPSG","7022"]],TOWGS84[-87,-98,-121,0,0,0,0],AUTHORITY["EPSG","6230"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4230"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","23032"]]
```

The key thing to note here is that at the end of the shapefile WKT, the EPSG code of 23032 is defined, whereas this is not set for the raster.

If I convert the WKT to proj4, the raster resolves to: 
`+proj=utm +zone=32 +ellps=intl +units=m +no_defs`

this matches the definition provided [here](https://spatialreference.org/ref/epsg/ed50-utm-zone-32n/proj4/)

Unfortunately, if I try to convert the shapefile, it resolves to `+init=epsg:23032` - which, as far as I understand, is a different way of defining the same CRS.

This issue is not completely resolved, but a quick but very hacky workaround I have implemented is to use fuzzy string matching. If the EPSG code is not set, then see if the WKT is at least 70% similar - if so, proceed with the processing.

Relevant branch:
https://github.com/MamadioCMCC/HazardRiskScripts/tree/crs-issue

This involves an extra dependency, which I added to the conda environment spec.

To install manually:

```bash
$ conda install -c conda-forge fuzzywuzzy
```

This issue has to be addressed more comprehensively, but I'll need more time to do it.
